# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/APoniatowski/GoSSH
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go build -i -race -v
      # - run: go build -i -msan -v   # Failing at this step with Permission Denied errors 

test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/APoniatowski/GoSSH
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go run -v main.go
      - run: go test -v ./...
