# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/APoniatowski/GoSSH
    steps:
      - checkout # Checks out the source code
      - run: go get -v -t -d ./...
      - run:
          name: Build the executable
          command: |
            echo "Starting compilation..."
            go build -i -race -v
      # - run: go build -i -msan -v   # Failing at this step with Permission Denied errors 
      - persist_to_workspace:
          root: . # Persist current working directory
          paths: ./* # Glob. Will persist everything in folder
      - store_artifacts:
          path: ./GoSSH # executable

test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/APoniatowski/GoSSH
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: go get -v -t -d ./...
      - run: go run -v main.go
      - run: go test -v

workflows:
  version: 2
  build_test:
    jobs:
    - build
    - test:
        requires:
            - build