---
ServerList:
  Server1:
    FQDN: hostname1.whatever.com
    Username: user
    Password: password
    Key_Path: /path/to/key
  Server2:
    FQDN: hostname2.whatever.com
    Username: user2
    Password: password2
    Key_Path: /path/to/key