ServerGroup1:
  Server11:
    FQDN: hostname11.whatever.com
    Username: user11
    Password: password11
    Key_Path: /path/to/key
    Port: 22
    Need_Sudo: false
  Server12:
    FQDN: hostname12.whatever.com
    Username: user12
    Password: password12
    Key_Path: /path/to/key
    Port: 223
    Need_Sudo: true
ServerGroup2:
  Server21:
    FQDN: hostname21.whatever.com
    Username: user21
    Password: password21
    Key_Path: /path/to/key
    Port: 2233
    Need_Sudo: false
  Server22:
    FQDN: hostname22.whatever.com
    Username: user22
    Password: password22
    Key_Path: /path/to/key
    Port: 
    Need_Sudo: true
