Server Group 1:     #group name, spacing does not matter
  Server 1:         #server name, spacing does not matter
    FQDN: hostname11.whatever.com #         FQDN, is needed. Username defaults to root,
    Username: user11              ##        password or key needed, ports default to 22
    Password: password11          ###       and OS will include all package managers per OS.
    Key_Path: /path/to/key        ###       If sudo is required, passwords will be needed.
    Port: 22                      ##        I will add the ability to use encrypted passwords.
    OS: debian                    #         This file should not be on a shared directory in anyway.
  Server 2:
    FQDN: hostname12.whatever.com
    Username: user12
    Password: password12
    Key_Path: /path/to/key
    Port: 223
    OS: centos    # or rhel
Server Group 2:
  Server 1:
    FQDN: hostname21.whatever.com
    Username: user21
    Password: password21
    Key_Path: /path/to/key
    Port: 2233
    OS: fedora
  Server 2:
    FQDN: hostname22.whatever.com
    Username: user22
    Password: password22
    Key_Path: /path/to/key
    Port:
    OS: opensuse  # or sles
