Master K8s Group:
  Ubuntu 20.04:
    FQDN: ubuntu-test-1
    Username: test
    Password: test
    OS: ubuntu
Slave K8s group:
  Opensuse Leap:
    FQDN: opensuse-test-1
    Username: test
    Password: test
    OS: opensuse
  Centos 8:
    FQDN: centos-test-1
    Username: test
    Password: test
    OS: centos
